// <auto-generated />
using System;
using GamePanel.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamePanel.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909235900_AddRuntimeAdoption")]
    partial class AddRuntimeAdoption
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("GamePanel.Domain.Entities.ServerInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackupPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DataPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallationPath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstanceKey")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProcessId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProvisioningMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ready")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReadinessMarker")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RuntimeId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RuntimeType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SteamAppId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorldName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstanceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_ServerInstances_InstanceKey")
                        .HasFilter("\"InstanceKey\" IS NOT NULL");

                    b.HasIndex("RuntimeType", "RuntimeId")
                        .IsUnique()
                        .HasDatabaseName("UX_ServerInstances_RuntimeType_RuntimeId")
                        .HasFilter("\"RuntimeId\" IS NOT NULL");

                    b.ToTable("ServerInstances", (string)null);
                });

            modelBuilder.Entity("GamePanel.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedUsername");

                    b.ToTable("Users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
