import { useCallback, useEffect, useState } from "react";
import type { AuthProvider } from "../../auth";
import { Btn } from "../common";

type AuditItem = { id: number; createdAtUtc: string; usernameSnapshot: string; action: string; isSuccess: boolean; resultCode?: string | null; metadataJson?: string | null };
type AuditPage = { items: AuditItem[]; total: number; page: number; pageSize: number; hasMore: boolean };

function iso(value: string) { return value ? new Date(value).toISOString() : undefined; }

export default function AuditLogView({ auth, serverId }: { auth: AuthProvider; serverId?: string }) {
  const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [type, setType] = useState(""); const [resultCode, setResultCode] = useState("");
  const [page, setPage] = useState(1); const [data, setData] = useState<AuditPage | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async (targetPage = page) => { setLoading(true); setError(""); try { setData(await auth.auditLogs({ serverId, fromUtc: iso(from), toUtc: iso(to), type, resultCode, page: targetPage, pageSize: 25 })); setPage(targetPage); } catch (e: any) { setError(e.message ?? "Failed to load audit logs"); } finally { setLoading(false); } }, [auth, serverId, from, to, type, resultCode, page]);
  useEffect(() => { void load(1); }, [serverId]);
  return <div className="detail-section"><div className="status-panel-header"><div><h4>Audit logs</h4><p className="muted">Structured status/metric events · retention 7 days · raw logs are not stored</p></div><Btn variant="ghost" busy={loading} onClick={() => void load(1)}>Refresh</Btn></div><div className="log-controls"><label>From <input type="datetime-local" value={from} onChange={e => setFrom(e.target.value)} className="sm-input" /></label><label>To <input type="datetime-local" value={to} onChange={e => setTo(e.target.value)} className="sm-input" /></label><select value={type} onChange={e => setType(e.target.value)} className="sm-input"><option value="">All types</option><option value="STATUS_CALL">STATUS_CALL</option><option value="METRIC_CALL">METRIC_CALL</option><option value="START_SERVER">START_SERVER</option><option value="STOP_SERVER">STOP_SERVER</option><option value="UPDATE_CONFIG">UPDATE_CONFIG</option></select><input value={resultCode} onChange={e => setResultCode(e.target.value)} placeholder="Result code" className="log-filter-input" /><Btn variant="ghost" onClick={() => void load(1)}>Filter</Btn></div>{error && <p className="config-msg">{error}</p>}<div className="audit-list">{data?.items.map(item => <div className="audit-row" key={item.id}><span className="muted">{new Date(item.createdAtUtc).toLocaleString()}</span><strong className={item.isSuccess ? "audit-ok" : "audit-fail"}>{item.action}</strong><span>{item.resultCode ?? "—"}</span><span>{item.usernameSnapshot}</span><span className="muted">{item.metadataJson ?? "{}"}</span></div>)}{!loading && data?.items.length === 0 && <p className="empty-state">No audit records</p>}</div>{data && <div className="status-panel-header"><span className="muted">Showing page {data.page} · {data.total} records</span><div className="action-btns"><Btn variant="ghost" disabled={data.page <= 1 || loading} onClick={() => void load(data.page - 1)}>Previous</Btn><Btn variant="ghost" disabled={!data.hasMore || loading} onClick={() => void load(data.page + 1)}>Next</Btn></div></div>}</div>;
}
