import { useState } from "react";
import type { AuthProvider, Server } from "../../auth";
import { Btn } from "../common";
import ServerCard from "./ServerCard";

type Point = { windowStartUtc: string; warningCount: number; errorCount: number; fatalCount: number; playerJoinCount: number; playerLeaveCount: number };

export function GlobalMetrics({ metrics, points }: { metrics: any; points: Point[] }) {
  if (!metrics) return null;
  const cards = [["Running", metrics.runningServers, "var(--green)"], ["Ready", metrics.readyServers, "var(--accent)"], ["Stopped", metrics.stoppedServers, "var(--red)"], ["Errors 24h", metrics.errorCount24h, "var(--orange)"], ["Fatal 24h", metrics.fatalCount24h, "var(--red)"]];
  const series = points.slice().reverse().slice(-24);
  const sum = (key: keyof Point) => series.reduce((n, p) => n + Number(p[key] ?? 0), 0);
  const max = Math.max(1, ...series.map(p => p.warningCount + p.errorCount + p.fatalCount));
  const bars = series.map((p, i) => { const x = i * 100 / Math.max(1, series.length); const width = Math.max(2, 82 / Math.max(1, series.length)); const scale = 100 / max; const fatal = p.fatalCount * scale; const error = p.errorCount * scale; const warning = p.warningCount * scale; return <g key={i}><rect x={x} y={100 - fatal} width={width} height={fatal} className="chart-bar fatal-bar" /><rect x={x} y={100 - fatal - error} width={width} height={error} className="chart-bar error-bar" /><rect x={x} y={100 - fatal - error - warning} width={width} height={warning} className="chart-bar warning-bar" /></g>; });
  return <><div className="metrics-strip">{cards.map(([label, value, color]) => <div className="metric-card" key={String(label)}><span>{label}</span><strong style={{ color: String(color) }}>{String(value ?? 0)}</strong></div>)}</div><div className="metrics-dashboard"><div className="chart-card"><div className="chart-header"><div><h3>Log health</h3><span>Warning, error and fatal events · 24h</span></div><strong>{sum("warningCount") + sum("errorCount") + sum("fatalCount")} events</strong></div><svg className="metric-chart" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Log health chart"><line x1="0" y1="99" x2="100" y2="99" className="chart-axis" />{bars}</svg><div className="chart-legend"><span><i className="legend-dot warning" />Warnings {sum("warningCount")}</span><span><i className="legend-dot error" />Errors {sum("errorCount")}</span><span><i className="legend-dot fatal" />Fatal {sum("fatalCount")}</span></div></div><div className="chart-card"><div className="chart-header"><div><h3>Player activity</h3><span>Join and leave events · 24h</span></div><strong>{sum("playerJoinCount") + sum("playerLeaveCount")} events</strong></div><div className="activity-bars">{series.map((p, i) => <div className="activity-column" key={i} title={new Date(p.windowStartUtc).toLocaleString()}><span className="join-bar" style={{ height: `${Math.min(100, p.playerJoinCount * 18 + (p.playerJoinCount ? 8 : 0))}%` }} /><span className="leave-bar" style={{ height: `${Math.min(100, p.playerLeaveCount * 18 + (p.playerLeaveCount ? 8 : 0))}%` }} /></div>)}</div><div className="chart-legend"><span><i className="legend-dot join" />Joins {sum("playerJoinCount")}</span><span><i className="legend-dot leave" />Leaves {sum("playerLeaveCount")}</span></div></div></div></>;
}

export function MetricsExplorer({ auth, servers, initial }: { auth: AuthProvider; servers: Server[]; initial: Point[] }) {
  const [rows, setRows] = useState<any[]>(initial);
  const [serverId, setServerId] = useState(""); const [severity, setSeverity] = useState("all");
  const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [loading, setLoading] = useState(false);
  const query = async () => { setLoading(true); try { setRows(await auth.aggregates({ limit: 288, serverId: serverId || undefined, fromUtc: from ? new Date(from).toISOString() : undefined, toUtc: to ? new Date(to).toISOString() : undefined })); } finally { setLoading(false); } };
  const visible = rows.filter(r => severity === "all" || (severity === "warning" && r.warningCount > 0) || (severity === "error" && r.errorCount > 0) || (severity === "fatal" && r.fatalCount > 0));
  const name = (id: string) => servers.find(s => s.id === id)?.name ?? id.slice(0, 8);
  return <div className="metric-explorer"><div className="explorer-header"><div><h3>Metric windows</h3><span>Stored aggregate rows, not raw console logs</span></div><span className="server-count">{visible.length}</span></div><div className="metric-filters"><select value={serverId} onChange={e => setServerId(e.target.value)}><option value="">All servers</option>{servers.map(s => <option value={s.id} key={s.id}>{s.name}</option>)}</select><select value={severity} onChange={e => setSeverity(e.target.value)}><option value="all">All severities</option><option value="warning">Warnings</option><option value="error">Errors</option><option value="fatal">Fatal</option></select><input type="datetime-local" value={from} onChange={e => setFrom(e.target.value)} /><input type="datetime-local" value={to} onChange={e => setTo(e.target.value)} /><Btn variant="ghost" busy={loading} onClick={query}>Filter</Btn></div><div className="metric-table-wrap"><table className="metric-table"><thead><tr><th>Window UTC</th><th>Server</th><th>Warn</th><th>Error</th><th>Fatal</th><th>Joins</th><th>Leaves</th><th>Last error</th></tr></thead><tbody>{visible.map(r => <tr key={`${r.serverInstanceId}-${r.windowStartUtc}`}><td>{new Date(r.windowStartUtc).toLocaleString()}</td><td>{name(r.serverInstanceId)}</td><td className={r.warningCount ? "metric-warning" : ""}>{r.warningCount}</td><td className={r.errorCount ? "metric-error" : ""}>{r.errorCount}</td><td className={r.fatalCount ? "metric-fatal" : ""}>{r.fatalCount}</td><td>{r.playerJoinCount}</td><td>{r.playerLeaveCount}</td><td className="last-error-cell" title={r.lastErrorMessage ?? ""}>{r.lastErrorMessage || "—"}</td></tr>)}</tbody></table>{visible.length === 0 && <p className="empty-inline">No matching metric windows</p>}</div></div>;
}

export default function ServerListView({ servers, error, loading, metrics, aggregates, auth, onRefresh, onSelect }: { servers: Server[]; error: string; loading: boolean; metrics: any; aggregates: Point[]; auth: AuthProvider; onRefresh: () => void; onSelect: (s: Server) => void }) {
  return <><GlobalMetrics metrics={metrics} points={aggregates} /><MetricsExplorer auth={auth} servers={servers} initial={aggregates} /><div className="toolbar"><h2 className="section-title">Servers <span className="server-count">{servers.length}</span></h2><div className="toolbar-actions">{error && <p className="error-msg">{error}</p>}<Btn variant="ghost" onClick={onRefresh} disabled={loading}>&#8635; Refresh</Btn></div></div>{servers.length === 0 && !loading && <div className="empty-state"><span style={{ fontSize: 40 }}>📡</span><p>No servers found</p></div>}<div className="server-grid">{servers.map(s => <ServerCard key={s.id} server={s} onClick={() => onSelect(s)} />)}</div></>;
}