import { useEffect, useState } from "react";
import type { AuthProvider } from "../../auth";
import { Btn } from "../common";

type Settings = { combat: string; resourceRate: number; raidRate: string; deathPenalty: string; portalMode: string; passiveEnemies: boolean; playerBasedRaids: boolean; hammerMode: boolean; noBuildCost: boolean };
const defaults: Settings = { combat: "normal", resourceRate: 1, raidRate: "normal", deathPenalty: "normal", portalMode: "hard", passiveEnemies: false, playerBasedRaids: false, hammerMode: false, noBuildCost: false };

export default function ValheimSettings({ auth }: { auth: AuthProvider }) {
  const [settings, setSettings] = useState<Settings>(defaults); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { (async () => { try { const r = await auth.valheimSettings(); setSettings({ ...defaults, ...r.settings }); } catch (e: any) { setMessage(e.message ?? "Failed to load settings"); } finally { setLoading(false); } })(); }, [auth]);
  const set = <K extends keyof Settings>(key: K, value: Settings[K]) => setSettings(prev => ({ ...prev, [key]: value }));
  const save = async () => { setSaving(true); setMessage(""); try { const r = await auth.valheimSettingsUpdate(settings); setMessage(r.message ?? "Settings saved"); } catch (e: any) { setMessage(e.message ?? "Save failed"); } finally { setSaving(false); } };
  if (loading) return <div className="empty-state">Loading Valheim settings...</div>;
  return <div className="detail-section settings-panel"><div className="status-panel-header"><div><h4>World Modifiers</h4><p className="muted">Typed settings only; backend converts them to Valheim startup flags.</p></div><Btn busy={saving} onClick={save}>Save settings</Btn></div>{message && <p className="config-msg">{message}</p>}<div className="settings-grid"><label>Combat difficulty<select value={settings.combat} onChange={e => set("combat", e.target.value)}><option>veryeasy</option><option>easy</option><option>normal</option><option>hard</option><option>veryhard</option></select></label><label>Resource rate<select value={settings.resourceRate} onChange={e => set("resourceRate", Number(e.target.value))}><option value="0.5">0.5×</option><option value="1">1×</option><option value="2">2×</option><option value="3">3×</option></select></label><label>Raid frequency<select value={settings.raidRate} onChange={e => set("raidRate", e.target.value)}><option>none</option><option>less</option><option>normal</option><option>more</option><option>muchmore</option></select></label><label>Death penalty<select value={settings.deathPenalty} onChange={e => set("deathPenalty", e.target.value)}><option>casual</option><option>veryeasy</option><option>easy</option><option>normal</option><option>hard</option><option>hardcore</option></select></label><label>Portal mode<select value={settings.portalMode} onChange={e => set("portalMode", e.target.value)}><option>casual</option><option>hard</option><option>veryhard</option></select></label></div><div className="settings-toggles"><label><input type="checkbox" checked={settings.passiveEnemies} onChange={e => set("passiveEnemies", e.target.checked)} /> Passive enemies</label><label><input type="checkbox" checked={settings.playerBasedRaids} onChange={e => set("playerBasedRaids", e.target.checked)} /> Player-based raids</label><label><input type="checkbox" checked={settings.hammerMode} onChange={e => set("hammerMode", e.target.checked)} /> Hammer/build mode</label><label><input type="checkbox" checked={settings.noBuildCost} onChange={e => set("noBuildCost", e.target.checked)} /> No build cost</label></div><p className="muted settings-note">Changes require Valheim to be stopped and a launcher helper to apply the validated flags. Frontend never constructs command line arguments.</p></div>;
}
